version: '3.8'

services:
  koodera:
    image: registry.cn-hangzhou.aliyuncs.com/devops_hu/kooder:v1.0.1
    expose:
      - 8080
  kooderb:
    build: .
    expose:
      - 8080

  haproxy:
    image: haproxy:1.6
    volumes:
      - ./kooder.properties:/opt/kooder/kooder.properties:ro
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    links:
      - koodera
      - kooderb
    ports:
      - "8080:8080"



